### ISSUE TITLE
OST albums not grouped together in album section

### ISSUE THREAD

**Issue by DarkKaioken** [timusus/Shuttle2#145] opened 2023-12-09 22:11 UTC
## 🌎 Environment

- Environment: Production
- Device: Google Pixel 6a
- OS: Android 14
- App Version & Build:  1.0.6
- Possible Cause: [unknown]

## 💬 Description

Albums added to the S2 player that are original soundtracks are not being clustered together by their album name

## 🦶 Reproduction Steps

1. Download OST album to device
2. Open S2 player
3. Go to hamburger menu > Settings > Media > Rescan to import
4. See multiple album entries for OST in Album category

## 🤔 Expected Results

All music under the same album name for a soundtrack should be grouped together under the single soundtrack name as long as the name is identical

## 😲 Actual Results

Music for a soundtrack is being grouped together by their artist names creating multiple entries for the same album under the album category. 

## 📸 Screenshots

![Screenshot_20231209-144303](https://github.com/timusus/Shuttle2/assets/8249402/be904594-c339-4685-80ee-b27685e5f60f)

![Screenshot_20231209-144013](https://github.com/timusus/Shuttle2/assets/8249402/f0399031-b74f-40d9-8e74-4b80f0ba3306)

![Screenshot_20231209-144005](https://github.com/timusus/Shuttle2/assets/8249402/21a4d7ca-977a-4921-8b4e-773d5fcc0108)

![Screenshot_20231209-143953](https://github.com/timusus/Shuttle2/assets/8249402/49513af8-2596-489c-ace0-e1e5ca7cbfc2)

## 📎 Attachments

[Log file.pdf](https://github.com/timusus/Shuttle2/files/13625803/Log.file.pdf)

## 🤝 Relationships

- Related PRs or Issues: #xxx, #yyy

**Comment by DarkKaioken** [comment] 2023-12-09 23:15
!!! UPDATE!!! This occurs on any album that is a compilation of different artists, not just OST. Best of albums and genre compilation albums are also not grouping together.

![Screenshot_20231209-170229](https://github.com/timusus/Shuttle2/assets/8249402/423ea049-cf71-4ef6-b7ea-9de7e2cf38fe)

![Screenshot_20231209-170306](https://github.com/timusus/Shuttle2/assets/8249402/d3e472f3-462a-4a4e-85fb-942b0fa38cb6)

![Screenshot_20231209-170314](https://github.com/timusus/Shuttle2/assets/8249402/db56df2f-8674-45f3-9a6c-7929b63c6741)

**Comment by timusus** [comment] 2024-01-11 09:54
Shuttle handles this via the 'album-artist' tag. You need to set a common album-artist if you want these to be grouped together.

**Comment by DarkKaioken** [comment] 2024-01-11 17:03
Understood but why?  Shuttle uses the Artist tag. Why not use the Album tag? In metadata, the Album tag was solely intended to be used to ensure all songs from the same album would be grouped just as all songs by the same artist are grouped by the Artist tag.  

Besides, using the Album Artist tag doesn't fix the problem. It just verifies the issue.  Using that tag, albums still won't group as intended because that tag causes subdivision, especially for albums with songs by multiple artists like collaboration or genre albums (Best of R&B or 90's hits).  The trash would then show something like 90's hits Usher for one and 90's hits SWV for another causing two different entries, Even if they were hyphenated.   

Can this be changed in Shuttle?

**Comment by timusus** [comment] 2024-01-11 22:05
It's not as straightforward as it might seem. 

If we were to group together any songs that had the same album name, then any two albums which share the same name would end up being combined. A 'greatest hits' album for 2 different bands would end up being merged together.

So, you need something to differentiate the albums from each other. If you use the 'artist' metadata, it won't work for compilation albums, as each song has a different artist.

There needs to be some differentiator that is common for all songs that belong together on an album. In Shuttle, that differentiator is the 'album-artist'. 

So, my suggestion is to set the 'album-artist' tag to be the same for all songs that belong together on this album. Some people use 'Various Artists', for example.

**Comment by timusus** [comment] 2024-01-15 08:13
@DarkKaioken I'm gonna close this, as it is by design. Feel free to reopen if you want to discuss further.

**Closed by timusus** 2024-01-15 08:13 UTC
Labels: bug
